<Project Sdk="Aspire.AppHost.Sdk/13.6.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>2e080491-6caf-4129-b5e5-8b897be095b0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure.CognitiveServices" Version="13.6.0" />
    <PackageReference Include="Aspire.Hosting.Azure.Search" Version="13.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RagChat.Web\RagChat.Web.csproj" />
  </ItemGroup>

</Project>
